### ISSUE TITLE
Multivalue control issue, values not getting selected

### ISSUE THREAD

**Issue by rakeshteli111-sketch** [microsoft/vsts-extension-multivalue-control#382]
Not able to select values in the Multivalue Control Field. When trying to select, the values are not getting selected and are not displayed in the UI. This issue has been occurring since yesterday, after the last update to the extension.

**Comment by Cory-Jiggens** [comment]
We are seeing the same behavior and it happened with the update on Monday Nov 10th.  The version it was updated to v2.2.46

**Comment by jwolmanSymplr** [comment]
I am facing the same issue at our company where I have several (not all) of my Quality Engineers cannot select values in the Multicontrols and it seems to be growing every day of who cannot select values. This is happening on two different work item types. Bug and Test Case. When the user types in a value they check the check box then it disappears and nothing is selected. In the other one they open the drop down and they cannot check any of the boxes of the values in the list.

![Image](https://github.com/user-attachments/assets/c445b97a-a9ac-427c-afe5-5cebe44d634f)

I can select Test Category (see image) but I have several people in my org that cannot

Also does not work for Multicontrols that don't have pre-defined values, but I can type in a number and select it but others in my org cannot.

![Image](https://github.com/user-attachments/assets/c05b00eb-3ff9-499f-8ee2-8f833f3bfda1)


Installed version
2.2.47 (Latest)

Last updated
Nov 10, 2025 at 8:36 AM CST

**Comment by JessMol** [comment]
Other users have reported not being able to select the multi control values at all.

I have experienced a similar issue yesterday.  I was unable to select a multi control value after several attempts. I started with search option to narrow down the control option results, check the option, verified checked and my selection would not be retained.  I gave up using search to filter options and I scrolled down list to select the value.

Azure DevOps Services 11/2025. Windows 11 Enterprise build 22631.6060, Edge browser Version 141.0.3537.85 (Official build) (64-bit) Policy is managed at an Enterprise level. The MultiValue control version is 2.2.47 (Latest) Last updated Nov 10, 2025 at 7:36 AM MST

**Comment by jwolmanSymplr** [comment]
> Other users have reported not being able to select the multi control values at all.
> 
> I have experienced a similar issue yesterday. I was unable to select a multi control value after several attempts. I started with search option to narrow down the control option results, check the option, verified checked and my selection would not be retained. I gave up using search to filter options and I scrolled down list to select the value.
> 
> Azure DevOps Services 11/2025. Windows 11 Enterprise build 22631.6060, Edge browser Version 141.0.3537.85 (Official build) (64-bit) Policy is managed at an Enterprise level. The MultiValue control version is 2.2.47 (Latest) Last updated Nov 10, 2025 at 7:36 AM MST

My users cannot select values from a pre-defined list (so not searching, just open the drop down and try to select from 4 values was not working for them)

**Comment by jwolmanSymplr** [comment]
> [@sablevivek8](https://github.com/sablevivek8) Would you mind sharing some of your config? I am also on cloud but I see no issues...

For my org this is happening for some user, but the amount of users running into this issue seems to be growing daily.

**Comment by MOlausson** [comment]
We've released an update with a small change that we hope helps (we're still not able to repo in our environments), let us know if it makes any difference.

**Comment by JessMol** [comment]
> We've released an update with a small change that we hope helps (we're still not able to repo in our environments), let us know if it makes any difference.

I am still experiencing the same issue.   I select the field, I type most of the option's value, I select the option and see a checkbox, but it is not selected and the selected is not retained.  I see errors but do not know if directly related to this extension

<img width="1541" height="403" alt="Image" src="https://github.com/user-attachments/assets/fad399de-1278-45a3-acce-d7ccdbe220b8" />

**Comment by jwolmanSymplr** [comment]
> We've released an update with a small change that we hope helps (we're still not able to repo in our environments), let us know if it makes any difference.

It is still not working for a few people that I just spoke with. So it's still an issue in my organization.

**Comment by johnfox147** [comment]
@MOlausson and @mattiasen1 - Thank you for working to address this issue. This is affecting a large number of people in my organization. Would it be possible to try backing out the changes added 2 days ago when this was first observed?

**Comment by mattiasen1** [comment]
We will continue investigating. If you see any console logs, can you please share those?

**Comment by jwolmanSymplr** [comment]
> We will continue investigating. If you see any console logs, can you please share those?

Unfortunately the majority of the people in my organization facing this issue are in India and I am in the United States, so I will try to figure out how to get these logs from someone.

**Comment by jwolmanSymplr** [comment]
@MOlausson @mattiasen1 I appear to have found a work around for my team. If you use the keyboard and arrow down and then hit the Enter/Return key on the keyboard that seems to select values. It does not seem to select values by just trying to click the box using the mouse. I also tried to bring up the Chrome Dev Tools and it did not show any Network errors for my QE that was having the issue. Another weird issue with this is through Teams when I took control I could not duplicate it on her computer, once I stopped having control she did the EXACT same thing as me and she was still having the issue which is why I asked her to just type in a value and hit Enter and it worked. So using the keyboard seems to work to select values. And on the other field with a predefined list I just had to use the Select All and hit Enter/Return and it selected everything then she was able to select and deselect via the check boxes. So again we have a work around but it would still be nice to have this issue resolved. Thanks.

**Comment by JessMol** [comment]
> [@MOlausson](https://github.com/MOlausson) [@mattiasen1](https://github.com/mattiasen1) I appear to have found a work around for my team. If you use the keyboard and arrow down and then hit the Enter/Return key on the keyboard that seems to select values. It does not seem to select values by just trying to click the box using the mouse. I also tried to bring up the Chrome Dev Tools and it did not show any Network errors for my QE that was having the issue. Another weird issue with this is through Teams when I took control I could not duplicate it on her computer, once I stopped having control she did the EXACT same thing as me and she was still having the issue which is why I asked her to just type in a value and hit Enter and it worked. So using the keyboard seems to work to select values. And on the other field with a predefined list I just had to use the Select All and hit Enter/Return and it selected everything then she was able to select and deselect via the check boxes. So again we have a work around but it would still be nice to have this issue resolved. Thanks.

Yes. I agree and the information you have provided with keyboard strokes versus mouse clicks should be valuable information that can be use to isolate the issue with consideration of what was introduced with more recent update.

**Comment by MOlausson** [comment]
@johnfox147 @rajakonkala @ssullivan23 @JessMol @jwolmanSymplr @Cory-Jiggens @sablevivek8 @rakeshteli111-sketch and others, we've released another update that reverse some changes that we think may impact some users. We're still investigating but great if you can tell us if the latest fix helps for you.

**Comment by jwolmanSymplr** [comment]
> [@johnfox147](https://github.com/johnfox147) [@rajakonkala](https://github.com/rajakonkala) [@ssullivan23](https://github.com/ssullivan23) [@JessMol](https://github.com/JessMol) [@jwolmanSymplr](https://github.com/jwolmanSymplr) [@Cory-Jiggens](https://github.com/Cory-Jiggens) [@sablevivek8](https://github.com/sablevivek8) [@rakeshteli111-sketch](https://github.com/rakeshteli111-sketch) and others, we've released another update that reverse some changes that we think may impact some users. We're still investigating but great if you can tell us if the latest fix helps for you.

Thanks for the update and reversal of potential adverse code. I have reached out to my people in my org and have asked them if they start seeing any adverse issues from this latest update. Please keep us posted. Thanks.

**Comment by JessMol** [comment]
> > [@johnfox147](https://github.com/johnfox147) [@rajakonkala](https://github.com/rajakonkala) [@ssullivan23](https://github.com/ssullivan23) [@JessMol](https://github.com/JessMol) [@jwolmanSymplr](https://github.com/jwolmanSymplr) [@Cory-Jiggens](https://github.com/Cory-Jiggens) [@sablevivek8](https://github.com/sablevivek8) [@rakeshteli111-sketch](https://github.com/rakeshteli111-sketch) and others, we've released another update that reverse some changes that we think may impact some users. We're still investigating but great if you can tell us if the latest fix helps for you.
> 
> Thanks for the update and reversal of potential adverse code. I have reached out to my people in my org and have asked them if they start seeing any adverse issues from this latest update. Please keep us posted. Thanks.

My issue was when using the filter option. Today, if type the value, take focus off of the filter text box with mouse other than checkbox and then use mouse to select the checkbox of the value from the filtered list, it retains the selection.  If I leave focus in the text box and use mouse to immediately select the option displayed in the filtered list, it will not retain value. It still doesn't consistently select value.  I seem to keep trying different number of times each time and one of those attempts it works.

**Comment by rakeshteli111-sketch** [comment]
@MOlausson  @mattiasen1 - Thanks for update. Now it is working for me and checking with other team members.

My Observations is, it's working for MAC'os users, mostly Windows users are facing this issue. Please test in both OS when you are doing new changes. Thank you again,

**Comment by mattiasen1** [comment]
@JessMol Do you see anything in the logs that could help us further investigate this?

**Comment by ssullivan23** [comment]
> [@johnfox147](https://github.com/johnfox147) [@rajakonkala](https://github.com/rajakonkala) [@ssullivan23](https://github.com/ssullivan23) [@JessMol](https://github.com/JessMol) [@jwolmanSymplr](https://github.com/jwolmanSymplr) [@Cory-Jiggens](https://github.com/Cory-Jiggens) [@sablevivek8](https://github.com/sablevivek8) [@rakeshteli111-sketch](https://github.com/rakeshteli111-sketch) and others, we've released another update that reverse some changes that we think may impact some users. We're still investigating but great if you can tell us if the latest fix helps for you.

@MOlausson  - I confirmed with the user that she is working now.  Thanks to you and the collaborators for the attention and quick work.

**Comment by MOlausson** [comment]
@ssullivan23 thanks for confirming, happy to hear!

**Comment by mattiasen1** [comment]
As this seems to be resolved now, I will close this issue. Please reach out again if you encounter any other issues!
